### ISSUE TITLE
Centralized declaration of links

### ISSUE THREAD

**Issue by dvdrlee** [airbnb/DeepLinkDispatch#157]
Building off @RomainPiel's comment here https://github.com/airbnb/DeepLinkDispatch/issues/31#issuecomment-155389796 specifically the ability to declare links in a centralized place instead of having the annotations spread throughout the app. I'm curious to see if there are any ways to accomplish this now, or if anyone has ideas for implementing something like this in the future.

**Comment by felipecsl** [comment]
@dvdrlee the DeepLinkDispatch annotation processor will generate "loader" classes for each of your `@DeepLinkModule` annotated classes. The loader(s) will have all your deep links declared in a `REGISTRY` constant. That's an easy way you can see them in a centralized place (given you have your project already built, since the processor needs to run first). Also keep in mind that if you have multiple deep link modules, you'll have multiple loader classes too, one for each module.
There's a tradeoff here between having your deep links declared in a central place versus having them next to the Activity they are associated with. 
I believe we have a good compromise right now with the caveat being that you just need to built the project to be able to see all your deep links in a centralized place.
If this becomes a more popular request we can always re-evaluate the possibility of maybe having a gradle plugin with a DSL where you can declare them.
