### ISSUE TITLE
Regex wildcard support in 5.x

### ISSUE THREAD

**Issue by dobridog** [airbnb/DeepLinkDispatch#286]
After upgrading to version [5.1](https://github.com/airbnb/DeepLinkDispatch/releases/tag/5.1.0) from [4.1](https://github.com/airbnb/DeepLinkDispatch/releases/tag/v4.1.0) our tests indicated that the support for Regex wildcard matching dropped. This is a breaking change for us. Identified related issue #285 

The example below should work on v4.1 and match any variation of path segments. Since upgrade to major version 5.x this fails to match in [BaseRegistry](https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-base/src/main/java/com/airbnb/deeplinkdispatch/BaseRegistry.kt#L38)

```
/*
 Oversimplified example, but describes the intention to capture all variations of a weblink past the wildcard operation.
*/
@DeepLinkSpec(prefix = { "https://airbnb.com.*" })
public @interface WebDeepLink {
  String[] value();
}
```

Is there a migration path for supporting Wildcards? 

If this needs to be a feature request it would be nice to match the level of Regex  support [Android Path does](https://developer.android.com/guide/topics/manifest/data-element#path). This will allow natural handover from captured AppLinks to DeeplinkDispatch.

**Comment by rossbacher** [comment]
Regex path matching support was never a documented features and only worked because of an implementation detail. With the implementation changed this is not supported and there is no plan to support it (as I said it never was a feature).

You can submit a feature request but no idea when we could get to that as we don't use those features.
