### ISSUE TITLE
Support multiple schemes

### ISSUE THREAD

**Issue by felipecsl** [airbnb/DeepLinkDispatch#6]
Modify `@DeepLink` and `@DeepLinks` to also require the `scheme://` in the URI definition, so we can suport more than one scheme in `DeepLinkActivity`.

**Comment by andrewlord1990** [comment]
Seems like the scheme could be optional in the URI definition, then if you only use one scheme you don't need to specify it everywhere.

**Comment by felipecsl** [comment]
I think it's confusing to have it only sometimes require the scheme. It sounds like we should always enforce it for consistency.

**Comment by andrewlord1990** [comment]
That's a fair point. I was just thinking of when we recently switched our links from HTTP to HTTPS and only had to change it in the AndroidManifest, due to us having a different Deep linking activity (before using this library) for each scheme. I was thinking of this situation. However, it isn't really a common enough situation to worry about.

To be able to use the library, we will need multiple scheme support, so I am hoping to contribute this to the library. Will post on here when I start on it.
