### ISSUE TITLE
Variable schemes across flavors

### ISSUE THREAD

**Issue by tommyd3mdi** [airbnb/DeepLinkDispatch#75]
We have kind of a weird use case here - an app with three flavors and - of course - several activities, while one of the activity should deal with a certain set of URLs in one flavor and with another set of URLs in another. These URLs only differ in scheme and we already separated that out in the flavor's distinct manifests, i.e. we have `DeepLinkActivity` configured like this

* src/flavor1/AndroidManifest.xml with `<data android:scheme="ourscheme1" />`
* src/flavor2/AndroidManifest.xml with `<data android:scheme="ourscheme2" />`
* ...

While this should work in general (because each flavor gets its own manifest and will therefor only react on URLs of its very scheme), its still a bit ugly to have to define all possible flavor combinations on the specific activity, i.e.

    @DeepLink({"ourscheme1://some/path", "ourscheme2://some/path})
    public class SomeActivity extends Activity { ... }

Is there any way around this? Would it be possible to just define the path, without the scheme?

**Comment by felipecsl** [comment]
You could have different versions of the same activity, one for each one of your flavors, like you are doing with the AndroidManifest.xml file. Of course this would require delegating activity logic somewhere else in a common class to avoid duplication, but other than that, this approach should work fine.
DeepLinkDispatch's annotation processor is not aware of Android neither your app's flavor, so there's no way it could special-case that. Also I don't think it would make sense to do so, since this should be a concern of your application, not of the deep linking library you're using. Furthermore, currently the full URI is required for the `@DeepLink` annotation, so you can't omit the scheme

**Comment by droidekas** [comment]
@felipecsl I seem to have a similar requirement. And the form of delegation you mention would not be feasible in my case. 
I wanted your inputs on if this is possible? And what would have to be changed in the library for it. (I'd like to pick this up on a PR if you feel this is a valid feature and can be worked on).

**Comment by felipecsl** [comment]
You should be able to define your deep link constants in separate files per flavor, eg.:

`src/flavor1/java/com/example/DeepLinks.java`
```java
public interface DeepLinks {
  String DEEP_LINK_1 = "ourscheme1://some/path";
}
```

`src/flavor2/java/com/example/deep_links.java`
```java
public interface DeepLinks {
  String DEEP_LINK_1 = "ourscheme2://some/path";
}
```

`src/main/java/com/example/SomeActivity.java`
```java
@DeepLink(DEEP_LINK_1)
public class SomeActivity extends Activity {
}
```

Would this work for your case?

**Comment by droidekas** [comment]
My use case is:

The app comprises of 3 modules and an `app` modules:
Each module has deeplinks configured:
The app has 3 flavours which are configured on the app level. 
The modules are only available as aars(and hence cannot compile time configurations).
The App would have to propagate the deeplink scheme to different modules.
The Manifest changes can be handled because it would be from the app modules.
The modules do not differentiate between flavours.

Because of this setup, I would not be able to add different classes for flavours in my project :(
